title: Demo
description: test

baseurl: ""

markdown: kramdown
collections:
  products:
    output: true
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: [head, body]