title: Demo
description: test

plugins:
  - jekyll-admin

baseurl: ""

markdown: kramdown
collections:
  products:
    output: true
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: [head, body]
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration