backend:
  name: github
  repo: vnium/jekyll-template
  branch: gh-pages
  site_domain: jekyll-template.templateplay.com

media_folder: "images/uploads"

collections:
  - name: "products"
    label: "products"
    folder: "_products/"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "name", name: "name", widget: "string"}
      - {label: "image", name: "image", widget: "string"}
      - {label: "layout", name: "layout", widget: "string"}
      - {label: "true", name: "true", widget: "boolean"}